apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-monitoring'
    spec:
      project: my-project
      source:
        path: 'monitoring'
        repoURL: 'https://github.com/timo-herweg/argocd-example.git'
        targetRevision: HEAD
      destination:
        server: '{{url}}'
        namespace: default