apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: charts/grafana
    repoURL: https://github.com/grafana/helm-charts
    targetRevision: tags/grafana-6.41.0