apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-workload-cluster
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{nameNormalized}}-monitoring'
    spec:
      project: bwi
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
      source:
        path: 'apps/monitoring'
        repoURL: 'https://github.com/timo-herweg/argocd-example.git'
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: default