apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/grafana
    repoURL: 'https://github.com/grafana/helm-charts'
    targetRevision: grafana-5.6.12
    helm:
      parameters:
        - name: datasources.datasources.yaml.datasources.name[0]
          value: Prometheus
        - name: datasources.datasources.yaml.datasources.type[0]
          value: prometheus
        - name: datasources.datasources.yaml.datasources.url[0]
          value: http://prometheus-server:80
  project: my-project