apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/grafana
    repoURL: 'https://github.com/grafana/helm-charts'
    targetRevision: grafana-5.6.12
    helm:
      parameters:
        - name: datasources
          value: : |
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server:80
              access: direct
              isDefault: true
  project: my-project