apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/prometheus
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: prometheus-15.16.1
  project: my-project  