apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-monitoring'
    spec:
      project: bwi
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
      source:
        path: 'apps/monitoring'
        repoURL: 'https://github.com/timo-herweg/argocd-example.git'
        targetRevision: HEAD
      destination:
        server: '{{url}}'
        namespace: default